version: "3"

volumes:
  freeheat_test_local_postgres_data: {}
  freeheat_test_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: freeheat_test_local_django
    container_name: freeheat_test_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: freeheat_test_production_postgres
    container_name: freeheat_test_local_postgres
    volumes:
      - freeheat_test_local_postgres_data:/var/lib/postgresql/data
      - freeheat_test_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: freeheat_test_local_docs
    container_name: freeheat_test_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./freeheat_test:/app/freeheat_test:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: freeheat_test_local_redis

  celeryworker:
    <<: *django
    image: freeheat_test_local_celeryworker
    container_name: freeheat_test_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: freeheat_test_local_celerybeat
    container_name: freeheat_test_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: freeheat_test_local_flower
    container_name: freeheat_test_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  freeheat_frontend:
    build:
      context: ./
      dockerfile: ./compose/local/frontend/Dockerfile
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
