/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * freeheat_test API
 * Documentation of API endpoints of freeheat_test
 * OpenAPI spec version: 1.0.0
 */

/**
 * Unspecified response body
 */
export type ApiEnergyLogsUploadCsvCreate400 = {[key: string]: unknown};
