/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * freeheat_test API
 * Documentation of API endpoints of freeheat_test
 * OpenAPI spec version: 1.0.0
 */

export type ApiSchemaRetrieveFormat = typeof ApiSchemaRetrieveFormat[keyof typeof ApiSchemaRetrieveFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiSchemaRetrieveFormat = {
  json: 'json',
  yaml: 'yaml',
} as const;
