/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * freeheat_test API
 * Documentation of API endpoints of freeheat_test
 * OpenAPI spec version: 1.0.0
 */

export type ApiUserCarChargeLogsListParams = {
/**
 * Number of results to return per page. 
 Default is 20
 */
itemsPerPage?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
};
