/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * freeheat_test API
 * Documentation of API endpoints of freeheat_test
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedUserCarModel {
  readonly id?: number;
  name?: string;
  model?: string;
  year?: number;
  max_energy?: string;
  current_energy?: string;
  is_charging?: boolean;
  is_active?: boolean;
  readonly owner?: number;
}
