/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * freeheat_test API
 * Documentation of API endpoints of freeheat_test
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import {
  faker
} from '@faker-js/faker'

export const getAuthTokenCreateMock = () => ({username: faker.random.word(), password: faker.random.word(), token: faker.random.word()})

export const getAuthTokenMSW = () => [
rest.post('*/auth-token/', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getAuthTokenCreateMock()),
        )
      }),]
