# Generated by Django 4.2.5 on 2023-09-19 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("max_energy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_energy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_charging", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Car",
                "verbose_name_plural": "User Cars",
                "ordering": ["name"],
                "unique_together": {("name", "model", "year", "owner")},
            },
        ),
        migrations.CreateModel(
            name="EnergyPriceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Energy Price Log",
                "verbose_name_plural": "Energy Price Logs",
                "ordering": ["price"],
                "unique_together": {("price",)},
            },
        ),
        migrations.CreateModel(
            name="UserCarChargeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("energy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_charging", models.BooleanField(default=False)),
                (
                    "user_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_car_charge_logs",
                        to="energy_prices.usercar",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Car Horuly Charge Log",
                "verbose_name_plural": "User Car Charge Logs",
                "ordering": ["user_car"],
                "unique_together": {("user_car", "energy", "is_charging")},
            },
        ),
    ]
