# Generated by Django 4.2.5 on 2023-09-20 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy_prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercarchargelog",
            unique_together=set(),
        ),
    ]
