# Generated by Django 4.2.5 on 2023-09-20 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy_prices", "0002_alter_usercarchargelog_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="energypricelog",
            unique_together={("price", "created_at")},
        ),
    ]
