# Generated by Django 4.2.5 on 2023-09-20 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy_prices", "0003_alter_energypricelog_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="energypricelog",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Energy Price Log",
                "verbose_name_plural": "Energy Price Logs",
            },
        ),
    ]
